(define (problem BookPlanner-1deseado-1leido-5libros)
   (:domain BookPlanner)
   (:objects 
      HarryPotter_4 Vengadores - pendiente
      HarryPotter_1 HarryPotter_2 HarryPotter_3 IronMan Hulk - normal
      antes enero febrero marzo abril mayo junio julio agosto septiembre octubre noviembre diciembre - tiempo
    )

  (:init
    (= (coste) 0)
    (= (mes) 1)
    (= (num enero) 1)
    (= (num febrero) 2)
    (= (num marzo) 3)
    (= (num abril) 4)
    (= (num mayo) 5)
    (= (num junio) 6)
    (= (num julio) 7)
    (= (num agosto) 8)
    (= (num septiembre) 9)
    (= (num octubre) 10)
    (= (num noviembre) 11)
    (= (num diciembre) 12)
    (= (paginasLibres enero) 800)
    (= (paginasLibres febrero) 800)
    (= (paginasLibres marzo) 800)
    (= (paginasLibres abril) 800)
    (= (paginasLibres mayo) 800)
    (= (paginasLibres junio) 800)
    (= (paginasLibres julio) 800)
    (= (paginasLibres agosto) 800)
    (= (paginasLibres septiembre) 800)
    (= (paginasLibres octubre) 800)
    (= (paginasLibres noviembre) 800)
    (= (paginasLibres diciembre) 800)
    (= (paralelo IronMan) 1)
    (= (paralelo Hulk) 1)
    (= (paralelo Vengadores) 0)
    (= (paralelo HarryPotter_1) 0)
    (= (paralelo HarryPotter_2) 0)
    (= (paralelo HarryPotter_3) 0)
    (= (paralelo HarryPotter_4) 0)
    (leido HarryPotter_1)
    (completado HarryPotter_1)
    (= (mes_lectura HarryPotter_1 ) 0)
    (precondicion HarryPotter_2 HarryPotter_1)
    (precondicion HarryPotter_3 HarryPotter_2)
    (precondicion HarryPotter_4 HarryPotter_3)
    (precondicion Vengadores IronMan)
    (precondicion Vengadores Hulk)
    (tien_prec HarryPotter_2)
    (tien_prec HarryPotter_3)
    (tien_prec HarryPotter_4)
    (tien_prec Vengadores)
    (= (paginas HarryPotter_1) 200)
    (= (paginas HarryPotter_2) 200)
    (= (paginas HarryPotter_3) 200)
    (= (paginas HarryPotter_4) 200)
    (= (paginas Hulk) 800)
    (= (paginas IronMan) 800)
    (= (paginas Vengadores) 100)
  )
  (:metric minimize (coste))
  (:goal (forall (?p - pendiente) (completado ?p)))
)


